c -- $Id: COMBUD.h,v 1.2 2001/07/03 21:29:05 bill Exp $
c -- $Source: /usr/local/portgcm/src/cvsroot/genesis.2.2/Agcm/COMBUD.h,v $
c -- $Name:  $

C
CL            GLOBAL BUDGET QUANTITIES (SUBRS BUD* IN hisres.f)
C
C             IF THE NUMBER OF QUANTITIES IN /COMBUD/ IS CHANGED, 
C             RESET PARAMETER NBUDG HERE. (NBUDG AND TMBBUD(NBUDG) ARE 
C             WRITTEN TO RESTART FILE).
C
      PARAMETER (NBUDG = 30 + 31*NOREC)
C
      COMMON /COMBUD/
     +   BTIME0,    BTIME,    PE0,       PE,
     +   SE0,       SE,       KE0,       KE,
     +   WAVA0,     WAVA,     WLWC0,     WLWC,
     +   FPLUMT_G0, FPLUMT_G, FPLUMQ_G0, FPLUMQ_G,
     +   DMASS,     DMASSA,   DWFIX,     DWFIXA,
     +   TMPMIN,    MINTLO,   MINTLA,    MINTLV, 
     +   ITMMIN,    TMPMAX,   MAXTLO,    MAXTLA, 
     +   MAXTLV,    ITMMAX,
 
     +   DHCON(NOREC),   DHRADS(NOREC),  DHRADL(NOREC),  DRADTP(NOREC),
     +   DSOLIN(NOREC),  DSOLRF(NOREC),  DFIRTP(NOREC),  DMCLOUF(NOREC),
     +   DMCLOUC(NOREC), DMCLOUE(NOREC), DMCLOUS(NOREC), DHCLOUD(NOREC),
     +   DMREEV(NOREC),  DHREEV(NOREC),  DMPRECC(NOREC), DMPRECA(NOREC),
     +   DMPRECS(NOREC), DMCLOUP(NOREC), DMCLOUA(NOREC), DHVDIF(NOREC),
     +   DHHDIF(NOREC),  DKEVDF(NOREC),  DKEHDF(NOREC),  DRFLUX(NOREC),
     +   DSFLUX(NOREC),  DLFLUX(NOREC),  DEFLUX(NOREC),  DPFLUX(NOREC),
     +   DWNEG(NOREC),   DTAIR(NOREC),   DTOTCLD(NOREC)
C
      REAL
     +   KE0,    KE,
     +   MINTLO, MINTLA, MINTLV, ITMMIN,
     +   MAXTLO, MAXTLA, MAXTLV, ITMMAX
C
      DIMENSION TMPBUD(NBUDG)
      EQUIVALENCE (BTIME0,TMPBUD)
C
C             BUDGET-RELATED CONSTANTS
C
      COMMON /COMBUD1/ COSBUD(NOREC), BUDFREQ,  DTTOL, NBUDGPRE

