#!/bin/csh -fx

set exp = snof
set EXP = `echo $exp | tr "[a-z]" "[A-Z]"`

set vegtype   = 0               # 0=D+S, 1=wisc, 2/3=eve/leaf, 4,5=biome
set oceantype = 1               # 0=presc SST, 1 = slab, 2 = ogcm
set resa      = T31             # R15,T31,... = agcm resol
set ress      = T31             # R15,T31,2X2 = surface resol
set pshell = ''

set nonomatch

#--------------


set host = `hostname -s`
set hostpre = `echo $host | cut -b1-6`
if ($hostpre == 'lionxo' || $hostpre == 'lionxc') set host = lion
set hostsys = linux
echo "host = $host"

if ($host == 'neptune' || $host == 'venus') then
  set H = ~alr335/Genesis.3.0
  set R = ~/Genesis.3.0
else if ($host == 'lion') then
  set H = /gpfs/home/dxp21
  set R = /gpfs/scratch/dxp21
else
  echo "unknown host $host"
  exit (-1)
endif

#set STOREXE      = $H/Genesis.3.0/Exec
#set STOREXE      = /gpfs/scratch/dxp21/Runsnoa
#set genexe       = genexe_T31_T31_ctl
 set STOREXE      = /gpfs/scratch/dxp21/Runsnof
 set genexe       = genexe_snof

set STOREDAT     = $H/Datafiles/V2
set STOREDATA    = $H/Datafiles/Aqua
set EVEIN        = $H/Genesis.3.0/Eve/leaff

set RUN           = $R/Run${exp}
cd $RUN

#-----------------

if ($1 != '' && $2 != '') then
  @ year_base = $1
  @ year      = $2
else
  @ year_base = 2001
  @ year      = 2001
endif

if ($year == $year_base) then
  set nsrest = -1
 #set nsrest =  0
 #rm -f nsre$exp
 #cp -p ${EXP}000RES nsre$exp
else
  set nsrest = 1
endif

@ yearlab = ($year - $year_base) + 1

if ($yearlab < 10) then
  set yearlab = "00$yearlab"
else if ($yearlab < 100) then
  set yearlab = "0$yearlab"
else if ($yearlab < 100) then
  set yearlab = $yearlab
endif

#---------

if ($3 != '') then
  set dtime = $3
else
  set dtime = 1800
endif

#---------

# for eve/leaf:
if ($vegtype == '2') then
  if (! -e leaff) mkdir leaff
  if (! -e leaff/leaf_file) then
    cp -p $EVEIN/leaf_file_001_2001 leaff/
    cp -p $EVEIN/leaf_file_001_2001 leaff/leaf_file
  endif
endif

#---------

cat >! interm << ENDINTERM
E\$INPUT

 ;           '----------------------'
  RUNTITLE = 'v3.0 $exp'
  NSREST   = $nsrest

  TEQCOLD = 280. ; 275.
  TPOCOLD = 280. ; 275.

  BASEDATE = '${year_base}/01/01'
 ;BASEDATE = '${year_base}/07/01'
  ENDDATE  = '${year}/12/31'

  MSNAMIN  = 'nsre$exp'
  MSNAMHIS= '${EXP}001','${EXP}002','${EXP}003','${EXP}004','${EXP}005',
            '${EXP}006','${EXP}007','${EXP}008','${EXP}009','${EXP}010',
            '${EXP}011','${EXP}012','${EXP}013','${EXP}014','${EXP}015',
            '${EXP}016','${EXP}017','${EXP}018','${EXP}019','${EXP}020',
            '${EXP}021','${EXP}022','${EXP}023','${EXP}024','${EXP}025',
            '${EXP}026','${EXP}027','${EXP}028','${EXP}029','${EXP}030',
            '${EXP}031','${EXP}032','${EXP}033','${EXP}034','${EXP}035',
            '${EXP}036','${EXP}037','${EXP}038','${EXP}039','${EXP}040',
            '${EXP}041','${EXP}042','${EXP}043','${EXP}044','${EXP}045',
            '${EXP}046','${EXP}047','${EXP}048','${EXP}049','${EXP}050'
            '${EXP}051','${EXP}052','${EXP}053','${EXP}054','${EXP}055',
            '${EXP}056','${EXP}057','${EXP}058','${EXP}059','${EXP}060'
            '${EXP}061','${EXP}062','${EXP}063','${EXP}064','${EXP}065',
            '${EXP}066','${EXP}067','${EXP}068','${EXP}069','${EXP}070'
            '${EXP}071','${EXP}072','${EXP}073','${EXP}074','${EXP}075',
            '${EXP}076','${EXP}077','${EXP}078','${EXP}079','${EXP}080'
            '${EXP}081','${EXP}082','${EXP}083','${EXP}084','${EXP}085',
            '${EXP}086','${EXP}087','${EXP}088','${EXP}089','${EXP}090'
            '${EXP}091','${EXP}092','${EXP}093','${EXP}094','${EXP}095',
            '${EXP}096','${EXP}097','${EXP}098','${EXP}099','${EXP}100'
  MSNAMRE2 = 'nsre$exp'
  MSPATH   = './'

 ;NSAVE    = 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334, 365
  NSAVE    = 365
  NNEXF    = 365

  NHISI    = 31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334, 365
  NDHIS    = 0

  CUSHNAM  = 'ORO*    ',  'TOPOG*  ',  'TOPOGUN*',
             'PS      ',  'PSLEV   ',  'Z200    ',  'Z500    ',
             'T       ',  'Q       ',  'U       ',  'V       ',
             'OMEGA   ',  'CLOUD   ',  'TOTCLD  ',
             'HFLR    ',  'QFLR    ',  'PRECL   ',  'PRECC   ',
             'SOLIN   ',  'SABTP   ',  'SABAT   ',  'FIRTP   ',
             'FRSA    ',  'FRLA    ',  'FRLD    ',  'SRAD    ',
             'FRSAV   ',  'FRSAN   ',  'FRSIV   ',  'FRSIN   ',
             'FRSAC  ', 
             'CLRST   ',  'CLRLT   ',  'CLRSS   ',  'CLRLS   ',
             'PBL03   ',  'PBL15   ',  'RHUMID  ',  'SURWIND ',
             'LWC     ',  'TOTLWC  ',  'RAINF   ',  'SNOWF   '

  SHOWMAPS  = .F.          BUDFREQ  = 365.
  LONOLSX   =   1          LATOLSX  =   1         TIMOLSX  = 0.
  OCEANTYPE = $oceantype
  VEGTYPE   = $vegtype
  HISNET = .T.
  DELEVTYPE = 0.
  DSBIOME = 11
  DEPTHLAKE = 0.
  SOILTEX = 333334

  QNORWEG = 0.
  QFACTOR = 0.
  QLIMIT  = 1000.
  QICEN   = 0.
  QICES   = 0.
  DEPTHICE = 10.          ; max sea ice thickness, applied at deb start
  DYNAMICE = .F.          ; dynamic sea ice
  DYNAMHEM = .F.          ; needed for sea ice at equator
  PRESCOUV = .F.          ; no prescribed ocean currents for sea ice 
  GWROUGH = 0.            ; gravity wave drag roughness (s.d. topog, m)

  ECCU  = 0.0             ;orbital params set for medium N and S summers
  OBLU  = 23.5
  PRECU = 0.0

  DTIME = $dtime

 ;================
 ;data input files:

  TOPOG_FILE     ='$STOREDATA/data_top_aqua_$resa'
  TOPOG2_FILE    ='$STOREDATA/data_top_aqua_$ress'
  SURFTYPE_FILE  ='$STOREDATA/data_sur_aqua_$ress'
  OZONE_FILE     ='$STOREDAT/data_ozone_$resa'   ; agcm ozone amount

 ;VEG_FILE       ='$STOREDAT/data_35ma_dsbiome_$ress'
 ;GWD_FILE       ='$STOREDAT/data_gwd_$resa'     ; agcm gravity wave drg
 ;WISCVEG_FILE   ='$STOREDAT/data_wisc_$ress'    ; Wisc veg (vegtype=1)
 ;FWATER_FILE    ='$STOREDAT/data_fwater_$ress'  ; open-water amount
 ;OCEANUV_FILE   ='$STOREDAT/data_ouv_$ress'     ; ocn u,v (oceantype=1)
 ;SST_FILE       ='$STOREDAT/data_sst_$ress'     ; sst/sice(oceantype=0)

 ;SOILTEX01_FILE ='$STOREDAT/data_soit01_$ress'  ; soil texture, layer 1
 ;SOILTEX02_FILE ='$STOREDAT/data_soit02_$ress'  ; soil texture, layer 2
 ;SOILTEX03_FILE ='$STOREDAT/data_soit03_$ress'  ; soil texture, layer 3
 ;SOILTEX04_FILE ='$STOREDAT/data_soit04_$ress'  ; soil texture, layer 4
 ;SOILTEX05_FILE ='$STOREDAT/data_soit05_$ress'  ; soil texture, layer 5
 ;SOILTEX06_FILE ='$STOREDAT/data_soit06_$ress'  ; soil texture, layer 6
 ;================

 \$END

 ;----------------------------------------------------------------------

E\$RADOTG

  SOLPAR  = 1367.   ; modern solar constant , W/m2 
  SOLFAC  = 0.94    ; multiplies SOLPAR

 ;CO2PPV  = 280.e-6 ; ppmv, preindustrial ~ 280.e-6
 ;CO2PPV  =  280.e-6  ; ppmv
  CO2PPV  = 1000.e-6  ; ppmv snoa, snoe, snof
 ;CO2PPV  = 1700.e-6  ; ppmv snob
 ;CO2PPV  = 2500.e-6  ; ppmv snoc
 ;CO2PPV  = 10000.e-6 ; ppmv snod

  CH4PPV  = 0.      ; ppmv, preindustrial ~ 0.8e-6
  N2OPPV  = 0.      ; ppmv, preindustrial ~ 0.288e-6
  F11PPV  = 0.      ; ppmv, preindustrial ~ 0.
  F12PPV  = 0.      ; ppmv, preindustrial ~ 0.

  O3FAC   = -1.     ; factor x modern ozone (lat vs z from file), def=1
 ;AERTAUVIS = 0.14  ; backgrd aerosol col. vis. optical depth, def=.14
  AERTAUVIS = 0.    ; Abbot et al. (JGR,2011) has zero aerosols

 \$END

 ;----------------------------------------------------------------------

E\$INPUTLSX

  CUSHNAM_A = 'LMASK*  ',  'HOCEAN* ',  'FWATER* ',
              'TS      ',  'TA      ',  'TS2     ',  'TS2_M   ',
              'WET1    ',  'WET2    ',  'WET3    ',
              'WET4    ',  'WET5    ',  'WET6    ',
              'WICE1   ',  'WICE2   ',  'WICE3   ',
              'WICE4   ',  'WICE5   ',  'WICE6   ',
              'SNOWH   ',  'SNOWF   ',  'ICEH    ',  'ICEF    ',
              'RUNOFF  ',  'DRAIN   ',  'TRANSP  ',  'AVAP    ',
              'TAUX    ',  'TAUY    ',  'QFLUX   ',  'RELHUM  ',
              'PRECIP  ',  'RAINFA  ',  'SNOWFA  ',
              'LAIT*   ',  'SAIT*   ',  'DSBIOME ',
              'INTVAP  ',  'SURVAP  ',  'FOGRAT  ',  
              'UICE    ',  'VICE    ',  'BRINE   ',
              'TOCEAN  ',  'HFLXOCN ',  'PMEOCN  '

  FICEMAXN = 1.
  FICEMAXS = 1.

 \$END
ENDINTERM

#-------------------------------------------------------------------

rm -f .assigngen fort.6 fort.[5-7][0-9] .jagen 
touch fort.6

sed  -e 's/^E/\ /g'  -e 's/;.*//g'  interm >! interma
mv interma interm

echo '=============='   >> fort.6
echo 'Namelist Input'   >> fort.6
echo '==============\n' >> fort.6
cat interm >> fort.6
echo '\n====================='   >> fort.6
echo   'End of Namelist Input'   >> fort.6
echo   '=====================\n' >> fort.6

#-------------

 unlimit
#setenv OMP_NUM_THREADS 4
 setenv OMP_NUM_THREADS 2
#setenv OMP_NUM_THREADS 1
 setenv OMP_DYNAMIC FALSE
 setenv KMP_STACKSIZE 10m

#-------------

# Run Genesis  

($pshell $STOREXE/$genexe < interm) >>& fort.6
if ($status != 0) exit ($status)
mv fort.6  fort.6_${yearlab}
#mv fort.50 fort.50_${yearlab}

$H/Conv/convnetonly              -lsx  ${exp}${yearlab}

exit (0)
