/* Life forms used in the life-form model */



char	life_form [110] [52] =
		{
         "  1. Equatorial Rainforest Broadleaf Trees         ",
         "  2. Equatorial-Montane Rainforest Broadleaf Trees ",
         "  3. Tropical Evergreen Microphyll-Broadleaf Trees ",
         "  4. Tropical-Monsoon Evergreen Broadleaf Trees    ",
         "  5. Tropical Evergreen Sclerophyll-Broadleaf Trees",
         "  6. Mediterranean Evergreen Broadleaf Trees       ",
         "  7. Warm-Temperate-Mesic Evergreen Broadleaf Trees",
         "  8. Warm-Temperate Evergreen Broadleaf Trees      ",
         "  9. Tropical-Monsoon Raingreen Broadleaf Trees    ",
         " 10. Tropical-Montane Raingreen Broadleaf Trees    ",
         " 11. Tropical-Xeric Raingreen Broadleaf Trees      ",
         " 12. Equatorial-Xeric Raingreen Broadleaf Trees    ",
         " 13. Western-Temperate Summergreen Broadleaf Trees ",
         " 14. Eastern-Temperate Summergreen Broadleaf Trees ",
         " 15. Eastern-Temp-Xeric Summergreen Broadleaf Trees",
         " 16. Cool-Temp/Boreal Summergreen Broadleaf Trees  ",
         " 17. Tropical Evergreen Linearleaf Trees           ",
         " 18. Tropical-Xeric Evergreen Needleleaf Trees     ",
         " 19. Mediterranean Evergreen Needleleaf Trees      ",
         " 20. Heliophilic Evergreen Needleleaf Trees        ",
         " 21. Warm-Temp-Montane Evergreen Needleleaf Trees  ",
         " 22. Temperate-Mesic Evergreen Needleleaf Trees    ",
         " 23. Western-Temperate Evergreen Needleleaf Trees  ",
         " 24. Eastern-Temperate Evergreen Needleleaf Trees  ",
         " 25. Cool-Temp/Boreal Evergreen Needleleaf Trees   ",
         " 26. Cool-Temp/Boreal Summergreen Needleleaf Trees ",
         " 27. Hydrophilic Summergreen Needleleaf Trees      ",
         " 28. Tropical Evergreen Broadleaf Small-Trees      ",
         " 29. Warm-Temperate Evergreen Broadleaf Small-Trees",
         " 30. Cool-Maritime Evergreen Broadleaf Small-Trees ",
         " 31. Tropical Raingreen Broadleaf Small-Trees      ",
         " 32. Temperate Summergreen Broadleaf Small-Trees   ",
         " 33. Temperate Evergreen Needleleaf Small-Trees    ",
         " 34. Tropical Evergreen Broadleaf Dwarf-Trees      ",
         " 35. Tropical-Montane Evergreen Dwarf-Trees        ",
         " 36. Temp-Montane/Boreal Needleleaf Dwarf-Trees    ",
         " 37. Palmiform Rosette-Trees                       ",
         " 38. Palmiform Small-Rosette-Trees                 ",
         " 39. Fern Small-Rosette-Trees                      ",
         " 40. Tropical-Montane Small-Rosette-Trees          ",
         " 41. Xeric Small-Rosette-Trees                     ",
         " 42. Raingreen Broadleaf Arborescent-Shrubs        ",
         " 43. Evergreen Broadleaf Arborescent-Shrubs        ",
         " 44. Summergreen Broadleaf Arborescent-Shrubs      ",
         " 45. Xeric Leafless Arborescent-Shrubs             ",
         " 46. Tropical Evergreen Broadleaf Shrubs           ",
         " 47. Hot-Desert Evergreen Broadleaf Shrubs         ",
         " 48. Desert Evergreen Leaf-Succulent Shrubs        ",
         " 49. Mediterranean Evergreen Broadleaf Shrubs      ",
         " 50. Mesic-Montane Evergreen Broadleaf Shrubs      ",
         " 51. Warm-Temperate Evergreen Broadleaf Shrubs     ",
         " 52. Cool-Temperate-Xeric Evergreen Shrubs         ",
         " 53. Temperate Summergreen Broadleaf Shrubs        ",
         " 54. Cool-Temp/Boreal Summergreen Broadleaf Shrubs ",
         " 55. Temperate-Xeric Summergreen Broadleaf Shrubs  ",
         " 56. Mediterranean Summergreen Broadleaf Shrubs    ",
         " 57. Mediterranean Evergreen Needleleaf Shrubs     ",
         " 58. Evergreen Needleleaf Shrubs                   ",
         " 59. Xeric Dwarf-Shrubs                            ",
         " 60. Mediterranean Dwarf-Shrubs                    ",
         " 61. Cool-Maritime Evergreen Dwarf-Shrubs          ",
         " 62. Cool-Temp/Boreal Evergreen Dwarf-Shrubs       ",
         " 63. Tundra Evergreen Dwarf-Shrubs                 ",
         " 64. Tundra Summergreen Dwarf-Shrubs               ",
         " 65. Cool-Maritime/Tropical-Alpine Cushion-Shrubs  ",
         " 66. Xeric Cushion-Shrubs                          ",
         " 67. Mesic Palmiform Rosette-Shrubs                ",
         " 68. Xeric Rosette-Shrubs                          ",
         " 69. Arborescent Stem-Succulents                   ",
         " 70. Branched Stem-Succulents                      ",
         " 71. Unbranched Stem-Succulents                    ",
         " 72. Arborescent Grasses                           ",
         " 73. Tall-Cane Grasses                             ",
         " 74. Sclerophyllous Grasses                        ",
         " 75. Tall Grasses                                  ",
         " 76. Short-Sward Graminoids                        ",
         " 77. Short-Bunch Graminoids                        ",
         " 78. Desert Short-Bunch Graminoids                 ",
         " 79. Temperate Tall Tussock-Graminoids             ",
         " 80. Temperate Short Tussock-Graminoids            ",
         " 81. Tropical-Montane Short Tussock-Graminoids     ",
         " 82. Cool-Maritime Short Tussock-Graminoids        ",
         " 83. Tundra Short Tussock-Graminoids               ",
         " 84. Tropical Evergreen Forbs                      ",
         " 85. Temperate Evergreen Forbs                     ",
         " 86. Succulent Forbs                               ",
         " 87. Raingreen Forbs                               ",
         " 88. Summergreen Forbs                             ",
         " 89. Desert Ephemeral Herbs                        ",
         " 90. Tropical-Alpine Raingreen Herbs               ",
         " 91. Tundra Summergreen Herbs                      ",
         " 92. Desert Cushion-Herbs                          ",
         " 93. Tropical-Montane Cushion-Herbs                ",
         " 94. Tundra Summergreen Cushion-Herbs              ",
         " 95. Tropical Liana Evergreen Vines                ",
         " 96. Evergreen Vines                               ",
         " 97. Raingreen Vines                               ",
         " 98. Summergreen Vines                             ",
         " 99. Tropical Broadleaf Epiphytes                  ",
         "100. Broadleaf Epiphytes                           ",
         "101. Narrowleaf Epiphytes                          ",
         "102. Evergreen Ferns                               ",
         "103. Summergreen Ferns                             ",
         "104. Mesic Peat-Forming Bryophytes                 ",
         "105. Mesic Bryophytes                              ",
         "106. Epiphytic Bryophytes                          ",
         "107. Mesic Lichens                                 ",
         "108. Boreal Lichens                                ",
         "109. Desert Cryptogams                             ",
         "110. Polar Cryptogams                              "

		};

